### PR TITLE
Fix some test cases of random forest classifier that do not work with multiple GPUs

### PR DESCRIPTION
**Pull request by lijinf2**
So that all nightly test cases get passed when using 2 GPUs.

### CODE REVIEW

**Comment by lijinf2** [comment]
build

**Review by eordentlich — COMMENTED** [review]
Good catch, but on further thought would it be better to change the test so that it works on 2 gpus?   Possible that ci upgrades in the future will allow 2 gpu testing.

**Comment by lijinf2** [comment]
build

**Review by eordentlich — APPROVED** [review]
👍

**Pull request merged**
