### PR TITLE
move python and jvm files into separate subdirectories

### PR DESCRIPTION
**Pull request by leewyang**

### CODE REVIEW

**Comment by leewyang** [comment]
build

**Comment by eordentlich** [comment]
Did you intend for the notebooks dir to be top level?

**Comment by leewyang** [comment]
> Did you intend for the notebooks dir to be top level?

Yes, that was the intent (since most repos have an "examples" folder at the top level).  But we can move it if you want.

**Comment by eordentlich** [comment]
Should the benchmark directory under python then be pulled out as well?  Maybe both go into a top level examples directory?   Also, do you know why the actual notebook files aren't showing as being moved?

**Comment by leewyang** [comment]
Tried to pull the benchmark directory up, but that started raising issues w/ black/isort formatting.  As for the notebooks, not sure what you mean... they're still in their original locations, just updated the links in the READMEs.

**Review by eordentlich — APPROVED** [review]
👍

**Pull request merged**
