### PR TITLE
[DO NOT MERGED] Add model type bound for typing

### PR DESCRIPTION
**Pull request by wbo4958**

### CODE REVIEW

**Comment by wbo4958** [comment]
build

**Review by leewyang — APPROVED** [review]

**Comment by wbo4958** [comment]
Oops, It's not gonna work on older pyspark (< 3.3.0) which doesn't have typing support especially no Generic[] for the Estimator. So it runs into the below exception,

``` console
tests/test_common_estimator.py:None (tests/test_common_estimator.py)
tests/test_common_estimator.py:41: in <module>
    from spark_rapids_ml.core import (
src/spark_rapids_ml/core.py:561: in <module>
    class _CumlEstimator(Estimator[M], _CumlCaller):
E   TypeError: 'ABCMeta' object is not subscriptable
``` 

So either  I can update the minimum pyspark requirement to 3.3.0  or  I just close this PR for now.  I prefer to close this PR temporarily. @leewyang @eordentlich any thoughts on this?

**Comment by leewyang** [comment]
I think it's fine to close this until we make pyspark 3.3.0 the minimum version.

**Comment by wbo4958** [comment]
Close this PR

**Pull request closed without merging**
