### PR TITLE
update rapids python deps to 23.08

### PR DESCRIPTION
**Pull request by eordentlich**
Note this is also changing the ci Dockerfile to pull in 23.08 release.   Should be changed to 23.10 nightly when we move to that branch.

### CODE REVIEW

**Comment by eordentlich** [comment]
build

**Comment by lijinf2** [comment]
LGTM. 

AWS-EMR (both notebook and benchmark) uses 23.6.0 in notebooks/aws-emr/init-bootstrap-action.sh. Do we want to update the version to 23.8.0?

**Comment by leewyang** [comment]
Should we also update `python/src/spark_rapids_ml/__init__.py`?

**Comment by eordentlich** [comment]
oops had some unsaved files in my editor

**Comment by eordentlich** [comment]
build

**Review by leewyang — APPROVED** [review]

**Pull request merged**
