### PR TITLE
Add a test case per 24.10 already supports all-zeroes feature vectors for sparse logistic regression

### PR DESCRIPTION
**Pull request by lijinf2**

### CODE REVIEW

**Comment by lijinf2** [comment]
build

**Review by eordentlich — COMMENTED** [review]
Did this test fail pre 24.10?

**Comment by lijinf2** [comment]
> Did this test fail pre 24.10?

Yeah, it failed in 24.08 with a cuda error related to map_then_reduce.

**Review by eordentlich — APPROVED** [review]
👍

**Pull request merged**
