### PR TITLE
enable single pass transform-evaluate for logistic regression

### PR DESCRIPTION
**Pull request by eordentlich**
note this PR includes cumulative changes from 
https://github.com/NVIDIA/spark-rapids-ml/pull/488
https://github.com/NVIDIA/spark-rapids-ml/pull/489

### CODE REVIEW

**Comment by eordentlich** [comment]
build

**Comment by eordentlich** [comment]
build

**Comment by eordentlich** [comment]
build

**Comment by lijinf2** [comment]
Overall looks good, except I am not very sure about the _ClassificationModelEvaluationMixIn class. Better to have Bobby or someone double-check and approve the PR.

**Review by wbo4958 — APPROVED** [review]
LGTM.

**Pull request merged**
