### PR TITLE
Validate num_workers

### PR DESCRIPTION
**Pull request by wbo4958**

### CODE REVIEW

**Comment by wbo4958** [comment]
build

**Comment by leewyang** [comment]
@wbo4958 looks like the build errors can be fixed with [this code](https://github.com/wbo4958/spark-rapids-ml/pull/1)

**Comment by leewyang** [comment]
build

**Comment by wbo4958** [comment]
> @wbo4958 looks like the build errors can be fixed with [this code](https://github.com/wbo4958/spark-rapids-ml/pull/1)

Oops, I should run all the tests. Thx @leewyang for the help

**Comment by wbo4958** [comment]
build

**Review by leewyang — APPROVED** [review]

**Pull request merged**
