### PR TITLE
Enable License header check

### PR DESCRIPTION
**Pull request by YanxuanLiu**
1. Enable `License header check` Github workflow
2. Add license header for files that are within the included scope and did not have a header before.

### CODE REVIEW

**Review by pxLi — APPROVED** [review]
+1 for CI update thanks. 

@eordentlich can you help double confirm the license header update for the codebase in this change, thanks

**Review by eordentlich — DISMISSED** [review]
Excellent.  Thanks for catching these and adding the check.
👍

**Comment by YanxuanLiu** [comment]
build

**Comment by YanxuanLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by YanxuanLiu** [comment]
Re-modified the files to avoid changing file permissions.

**Pull request merged**
