### PR TITLE
Move testing of large datasets into a new folder

### PR DESCRIPTION
**Pull request by lijinf2**
Followup of https://github.com/NVIDIA/spark-rapids-ml/pull/704

### CODE REVIEW

**Comment by lijinf2** [comment]
build

**Comment by lijinf2** [comment]
build

**Review by eordentlich — COMMENTED** [review]
minor comment, otherwise looks good.

**Comment by lijinf2** [comment]
build

**Review by eordentlich — APPROVED** [review]
👍

**Pull request merged**
