### PR TITLE
umap demo notebook

### PR DESCRIPTION
**Pull request by rishic3**
Notebook demonstrating umap functionality with comparison to local cpu umap, 

Currently, runtimes leave a lot to be desired; working on mitigating overheads to improve this. Additionally, the demo test dataset is pretty small (mnist, ~0.4 gb - good for visualization purposes). With a larger dataset, the efficiency of the spark implementation will be better demonstrated.

### CODE REVIEW

**Comment by rishic3** [comment]
build

**Comment by rishic3** [comment]
build

**Comment by rishic3** [comment]
build

**Comment by rishic3** [comment]
build

**Review by leewyang — APPROVED** [review]
As mentioned offline, would be nice to see a larger dataset.  Otherwise, LGTM.

**Pull request merged**
