### PR TITLE
Remove CUDA version definition in benchmark script [skip ci]

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Change default cuda version to 12.2.2, same as `spark-rapids-ml-benchmarking/benchmark/spark-rapids.sh`

### CODE REVIEW

**Comment by YanxuanLiu** [comment]
Test build:

https://github.com/YanxuanLiu/spark-rapids-ml/actions/runs/7137075866/job/19436497641

**Comment by YanxuanLiu** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Comment by YanxuanLiu** [comment]
re-built without CUDA version:

https://github.com/YanxuanLiu/spark-rapids-ml/actions/runs/7137780890/job/19438268097

**Comment by YanxuanLiu** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
It's good not set `cuda-version` to leverage the default cuda/driver defined in the GCP `spark-rapids.sh` file

**Pull request merged**
